name: Save Secret to File
on:
  workflow_dispatch:

jobs:
  save_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Save Secret to File
        run: echo "${{ secrets.TEST_SECRET }}" > test.key

      - name: Print to stdout
        run: cat test.key
